#!/usr/bin/env bash

REPO=https://github.com/ginkgo-project/ginkgo.git
TMPDIR=$(mktemp -d /tmp/git-tmp.XXXXXX)
GIT_DATA_DIR=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)/../git_data

git clone -n $REPO $TMPDIR

truncate -s 0 $GIT_DATA_DIR/branches

BRANCHES=$(git -C $TMPDIR branch -r | awk '{print $1}')
for BRANCH in $BRANCHES; do
  BRANCH=$(basename $BRANCH)
  if [[ $BRANCH != "HEAD" ]]; then
    echo $BRANCH >> $GIT_DATA_DIR/branches
    git -C $TMPDIR checkout $BRANCH
    git -C $TMPDIR --no-pager log --pretty=format:"%H %an %ad %s" --date=short > $GIT_DATA_DIR/$BRANCH
  fi
done

rm -rf $TMPDIR

