#!/usr/bin/env bash

REPO=https://github.com/ginkgo-project/ginkgo.git
TMPDIR=$(mktemp -d /tmp/git-tmp.XXXXXX)
GIT_DATA_DIR=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)/../git_data

git clone -n $REPO $TMPDIR

BRANCHES=$(git -C $TMPDIR branch -r | awk '{print $1}')
for BRANCH in $BRANCHES; do
  BRANCH=$(basename $BRANCH)
  if [[ $BRANCH != "HEAD" ]]; then
    git -C $TMPDIR checkout $BRANCH
    git -C $TMPDIR --no-pager log --pretty=format:"%H%x09%an%x09%ad%x09%s" --date=short | sed -r 's/[ \t]+/ /g' > $GIT_DATA_DIR/$BRANCH
  fi
done

rm -rf $TMPDIR

